import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Header
    nav: {
      home: 'Accueil',
      howItWorks: 'Comment ça marche',
      vehicleTypes: 'Véhicules rachetés',
      faq: 'FAQ',
      about: 'À propos',
      contact: 'Contact',
      estimate: 'Estimer ma voiture',
    },
    // Home page
    home: {
      heroTitle: 'Vendez votre voiture',
      heroTitleHighlight: 'au meilleur prix',
      heroSubtitle: 'Même en panne, accidentée ou sans contrôle technique. Estimation gratuite et rachat rapide partout en Belgique.',
      heroCta: 'Estimer ma voiture gratuitement',
      heroSecondary: 'Comment ça marche ?',
      trustBadge1: 'Paiement immédiat',
      trustBadge2: 'Enlèvement gratuit',
      trustBadge3: 'Toute condition',
      trustBadge4: 'Sans engagement',
      sectionWhyTitle: 'Pourquoi nous choisir ?',
      sectionWhySubtitle: 'Des milliers de Belges nous font confiance',
      why1Title: 'Rachat garanti',
      why1Desc: 'Nous rachetons tous les véhicules, peu importe leur état ou leur âge.',
      why2Title: 'Prix justes',
      why2Desc: 'Estimation transparente basée sur le marché réel.',
      why3Title: 'Service rapide',
      why3Desc: 'Offre sous 2h et enlèvement sous 48h.',
      why4Title: 'Zéro tracas',
      why4Desc: 'On s\'occupe de tout : papiers, enlèvement, paiement.',
      sectionHowTitle: 'Comment ça marche ?',
      sectionHowSubtitle: 'Vendez votre voiture en 3 étapes simples',
      how1Title: 'Décrivez votre véhicule',
      how1Desc: 'Remplissez notre formulaire en 2 minutes',
      how2Title: 'Recevez votre offre',
      how2Desc: 'Notre expert vous contacte sous 2h',
      how3Title: 'Vendez et encaissez',
      how3Desc: 'Paiement immédiat, enlèvement gratuit',
      sectionTypesTitle: 'Tous les véhicules acceptés',
      sectionTypesSubtitle: 'Quel que soit l\'état de votre voiture',
      type1: 'En bon état',
      type2: 'Avec problèmes',
      type3: 'En panne',
      type4: 'Accidentée',
      type5: 'Moteur HS',
      type6: 'Sans CT',
      sectionTestimonialsTitle: 'Ils nous font confiance',
      testimonial1: 'Service impeccable ! Ma vieille Clio a été rachetée en 24h. Je recommande.',
      testimonial1Author: 'Marie L., Bruxelles',
      testimonial2: 'J\'avais une voiture accidentée dont personne ne voulait. Ils m\'ont fait une offre correcte.',
      testimonial2Author: 'Jean-Pierre D., Liège',
      testimonial3: 'Rapide, efficace et honnête. Le prix proposé correspondait à mes attentes.',
      testimonial3Author: 'Sophie M., Namur',
      ctaTitle: 'Prêt à vendre votre voiture ?',
      ctaSubtitle: 'Obtenez une estimation gratuite en moins de 2 minutes',
      ctaButton: 'Estimer ma voiture maintenant',
    },
    // Estimation form
    estimation: {
      title: 'Estimation gratuite',
      subtitle: 'Remplissez le formulaire pour recevoir votre offre',
      step1: 'Véhicule',
      step2: 'Photos',
      step3: 'Contact',
      step4: 'Confirmation',
      // Step 1
      step1Title: 'Informations sur votre véhicule',
      brand: 'Marque',
      model: 'Modèle',
      year: 'Année',
      mileage: 'Kilométrage',
      fuel: 'Carburant',
      gearbox: 'Boîte de vitesse',
      condition: 'État du véhicule',
      registration: 'Immatriculation (optionnel)',
      desiredPrice: 'Prix souhaité (optionnel)',
      sellDelay: 'Quand souhaitez-vous vendre ? (optionnel)',
      select: 'Sélectionnez',
      selectCondition: 'Sélectionnez l\'état actuel',
      selectDelay: 'Sélectionnez un délai',
      // Fuel types
      fuelPetrol: 'Essence',
      fuelDiesel: 'Diesel',
      fuelHybrid: 'Hybride',
      fuelElectric: 'Électrique',
      fuelLpg: 'GPL',
      // Gearbox
      gearboxManual: 'Manuelle',
      gearboxAuto: 'Automatique',
      // Conditions
      conditionPerfect: 'Roule parfaitement',
      conditionIssues: 'Roule avec des problèmes',
      conditionBroken: 'Ne roule pas (panne)',
      conditionAccident: 'Accidenté',
      conditionEngineKO: 'Moteur HS',
      conditionNoCT: 'Sans contrôle technique',
      conditionOther: 'Autre',
      // Delays
      delayImmediate: 'Immédiatement',
      delay1Week: 'Sous 1 semaine',
      delay2Weeks: 'Sous 2 semaines',
      delay1Month: 'Sous 1 mois',
      delayNotUrgent: 'Pas pressé',
      // Step 2
      step2Title: 'Photos de votre véhicule (optionnel)',
      step2Desc: 'Ajoutez jusqu\'à 10 photos pour une estimation plus précise',
      uploadText: 'Cliquez ou glissez vos photos ici',
      uploadHint: 'PNG, JPG jusqu\'à 5MB chacune',
      maxPhotos: 'Maximum 8 photos autorisées',
      // Step 3
      step3Title: 'Vos coordonnées',
      fullName: 'Nom complet',
      phone: 'Téléphone',
      email: 'Email',
      postalCode: 'Code postal',
      city: 'Ville',
      rgpdConsent: 'J\'accepte que mes données soient utilisées pour traiter ma demande de rachat.',
      rgpdLink: 'Consultez notre politique de confidentialité',
      // Step 4
      step4Title: 'Récapitulatif de votre demande',
      vehicle: 'Véhicule',
      location: 'Localisation',
      photosAttached: 'photo(s) jointe(s)',
      callbackInfo: 'Nous vous rappelons sous 2 heures',
      callbackHours: 'Du lundi au samedi, de 9h à 19h',
      // Navigation
      previous: 'Précédent',
      next: 'Suivant',
      submit: 'Envoyer ma demande',
      submitting: 'Envoi en cours...',
      required: 'Requis',
      invalidEmail: 'Email invalide',
      invalidPhone: 'Numéro invalide',
      mustAccept: 'Vous devez accepter',
      errorSubmit: 'Une erreur est survenue. Veuillez réessayer.',
    },
    // Thank you page
    thankYou: {
      title: 'Merci pour votre demande !',
      subtitle: 'Votre demande a bien été enregistrée',
      reference: 'Référence',
      nextSteps: 'Prochaines étapes',
      step1: 'Notre expert analyse votre demande',
      step2: 'Vous recevez un appel sous 2h (jours ouvrés)',
      step3: 'Nous convenons d\'un rendez-vous',
      step4: 'Enlèvement gratuit et paiement immédiat',
      backHome: 'Retour à l\'accueil',
    },
    // How it works page
    howItWorks: {
      title: 'Comment ça marche ?',
      subtitle: 'Un processus simple et rapide en 4 étapes',
      step1Title: 'Remplissez le formulaire',
      step1Desc: 'Décrivez votre véhicule en quelques clics : marque, modèle, état, kilométrage. Ajoutez des photos pour une estimation plus précise.',
      step2Title: 'Recevez votre offre',
      step2Desc: 'Notre expert vous contacte sous 2 heures avec une proposition de rachat ferme et sans engagement.',
      step3Title: 'Acceptez et planifiez',
      step3Desc: 'Si notre offre vous convient, nous organisons l\'enlèvement de votre véhicule à la date qui vous arrange.',
      step4Title: 'Encaissez immédiatement',
      step4Desc: 'Lors de l\'enlèvement, vous recevez votre paiement. Nous nous occupons de tous les papiers administratifs.',
      ctaTitle: 'Prêt à commencer ?',
      ctaButton: 'Estimer ma voiture',
    },
    // Vehicle types page
    vehicleTypes: {
      title: 'Véhicules rachetés',
      subtitle: 'Nous rachetons tous les types de véhicules, quel que soit leur état',
      type1Title: 'Véhicules en bon état',
      type1Desc: 'Votre voiture roule parfaitement ? Nous vous proposons un prix juste basé sur le marché.',
      type2Title: 'Véhicules avec problèmes',
      type2Desc: 'Petits soucis mécaniques, électriques ou esthétiques ? Pas de problème, nous les rachetons.',
      type3Title: 'Véhicules en panne',
      type3Desc: 'Votre voiture ne démarre plus ? Nous nous déplaçons et l\'enlevons gratuitement.',
      type4Title: 'Véhicules accidentés',
      type4Desc: 'Accident léger ou grave, nous rachetons votre véhicule accidenté.',
      type5Title: 'Moteur HS',
      type5Desc: 'Moteur cassé, joint de culasse, turbo ? Nous faisons une offre.',
      type6Title: 'Sans contrôle technique',
      type6Desc: 'CT expiré ou refusé ? Nous rachetons votre véhicule sans conditions.',
      ctaTitle: 'Votre véhicule correspond ?',
      ctaButton: 'Demander une estimation',
    },
    // FAQ page
    faq: {
      title: 'Questions fréquentes',
      subtitle: 'Trouvez les réponses à vos questions',
      q1: 'Comment fonctionne le service de rachat ?',
      a1: 'C\'est simple : vous remplissez notre formulaire en ligne, nous vous contactons sous 2h avec une offre, et si elle vous convient, nous venons chercher votre véhicule et vous payons immédiatement.',
      q2: 'Quels types de véhicules rachetez-vous ?',
      a2: 'Nous rachetons tous les véhicules : en bon état, en panne, accidentés, sans contrôle technique, avec moteur HS... Peu importe la marque, le modèle ou l\'âge.',
      q3: 'L\'estimation est-elle gratuite ?',
      a3: 'Oui, l\'estimation est totalement gratuite et sans engagement. Vous êtes libre d\'accepter ou de refuser notre offre.',
      q4: 'Sous quel délai recevrai-je une offre ?',
      a4: 'Notre équipe vous contacte sous 2 heures ouvrées après réception de votre demande.',
      q5: 'Comment se passe le paiement ?',
      a5: 'Le paiement est effectué immédiatement lors de l\'enlèvement du véhicule, par virement bancaire ou en espèces selon votre préférence.',
      q6: 'L\'enlèvement est-il payant ?',
      a6: 'Non, l\'enlèvement de votre véhicule est totalement gratuit, où que vous soyez en Belgique.',
      q7: 'Quels documents dois-je fournir ?',
      a7: 'Vous devez fournir la carte grise (certificat d\'immatriculation), votre carte d\'identité, et si possible le carnet d\'entretien.',
      q8: 'Que se passe-t-il si ma voiture n\'a plus de contrôle technique ?',
      a8: 'Aucun problème ! Nous rachetons les véhicules sans CT valide. C\'est même notre spécialité.',
      q9: 'Rachetez-vous les véhicules qui ne roulent plus ?',
      a9: 'Oui, nous rachetons les véhicules en panne, immobilisés ou qui ne démarrent plus. Nous nous déplaçons avec un camion plateau.',
      q10: 'Dans quelles régions intervenez-vous ?',
      a10: 'Nous intervenons dans toute la Belgique : Wallonie, Bruxelles et Flandre.',
      q11: 'Combien de temps prend la procédure complète ?',
      a11: 'En général, entre la première prise de contact et l\'enlèvement de votre véhicule, comptez 24 à 48 heures.',
      q12: 'Puis-je annuler après avoir accepté l\'offre ?',
      a12: 'Oui, vous pouvez annuler à tout moment avant l\'enlèvement effectif du véhicule, sans frais ni pénalité.',
      stillQuestions: 'Vous avez d\'autres questions ?',
      contactUs: 'Contactez-nous',
    },
    // About page
    about: {
      title: 'À propos de nous',
      subtitle: 'Votre partenaire de confiance pour la vente de véhicules',
      intro: 'VendezVotreCar est né d\'un constat simple : vendre sa voiture, surtout quand elle a des problèmes, est souvent un parcours du combattant. Notre mission est de simplifier ce processus.',
      mission: 'Notre mission',
      missionText: 'Offrir à chaque Belge une solution simple, rapide et honnête pour vendre son véhicule, quel que soit son état.',
      values: 'Nos valeurs',
      value1Title: 'Transparence',
      value1Desc: 'Des prix clairs et des procédures expliquées.',
      value2Title: 'Rapidité',
      value2Desc: 'Offre sous 2h, enlèvement sous 48h.',
      value3Title: 'Respect',
      value3Desc: 'Un service client à l\'écoute et bienveillant.',
      stats: 'Quelques chiffres',
      stat1: 'Véhicules rachetés',
      stat2: 'Clients satisfaits',
      stat3: 'Années d\'expérience',
    },
    // Contact page
    contact: {
      title: 'Contactez-nous',
      subtitle: 'Une question ? N\'hésitez pas à nous contacter',
      formTitle: 'Envoyez-nous un message',
      name: 'Nom',
      email: 'Email',
      phone: 'Téléphone (optionnel)',
      message: 'Message',
      messagePlaceholder: 'Votre message...',
      send: 'Envoyer',
      sending: 'Envoi en cours...',
      success: 'Message envoyé avec succès !',
      error: 'Erreur lors de l\'envoi. Veuillez réessayer.',
      infoTitle: 'Nos coordonnées',
      phoneLabel: 'Téléphone',
      emailLabel: 'Email',
      hoursLabel: 'Horaires',
      hours: 'Lun-Sam : 9h-19h',
      zoneLabel: 'Zone d\'intervention',
      zone: 'Toute la Belgique',
    },
    // Footer
    footer: {
      description: 'Rachat de véhicules en Belgique. Tous types de véhicules acceptés : en panne, accidentés, sans contrôle technique.',
      quickLinks: 'Liens rapides',
      legal: 'Légal',
      legalNotice: 'Mentions légales',
      privacy: 'Confidentialité',
      cookies: 'Cookies',
      copyright: 'Tous droits réservés.',
    },
    // Cookie banner
    cookies: {
      message: 'Nous utilisons des cookies pour améliorer votre expérience.',
      learnMore: 'En savoir plus',
      accept: 'Accepter',
      reject: 'Refuser',
    },
    // Common
    common: {
      loading: 'Chargement...',
      error: 'Erreur',
      notFound: 'Non trouvé',
      back: 'Retour',
      close: 'Fermer',
    },
  },
  nl: {
    // Header
    nav: {
      home: 'Home',
      howItWorks: 'Hoe werkt het',
      vehicleTypes: 'Voertuigtypes',
      faq: 'FAQ',
      about: 'Over ons',
      contact: 'Contact',
      estimate: 'Schat mijn auto',
    },
    // Home page
    home: {
      heroTitle: 'Verkoop uw auto',
      heroTitleHighlight: 'aan de beste prijs',
      heroSubtitle: 'Zelfs bij pech, na een ongeluk of zonder keuring. Gratis schatting en snelle aankoop in heel België.',
      heroCta: 'Gratis schatting aanvragen',
      heroSecondary: 'Hoe werkt het?',
      trustBadge1: 'Directe betaling',
      trustBadge2: 'Gratis ophaling',
      trustBadge3: 'Elke toestand',
      trustBadge4: 'Vrijblijvend',
      sectionWhyTitle: 'Waarom ons kiezen?',
      sectionWhySubtitle: 'Duizenden Belgen vertrouwen ons',
      why1Title: 'Gegarandeerde aankoop',
      why1Desc: 'Wij kopen alle voertuigen, ongeacht hun staat of leeftijd.',
      why2Title: 'Eerlijke prijzen',
      why2Desc: 'Transparante schatting gebaseerd op de echte markt.',
      why3Title: 'Snelle service',
      why3Desc: 'Aanbod binnen 2 uur en ophaling binnen 48 uur.',
      why4Title: 'Geen gedoe',
      why4Desc: 'Wij regelen alles: papieren, ophaling, betaling.',
      sectionHowTitle: 'Hoe werkt het?',
      sectionHowSubtitle: 'Verkoop uw auto in 3 eenvoudige stappen',
      how1Title: 'Beschrijf uw voertuig',
      how1Desc: 'Vul ons formulier in binnen 2 minuten',
      how2Title: 'Ontvang uw aanbod',
      how2Desc: 'Onze expert belt u binnen 2 uur',
      how3Title: 'Verkoop en ontvang',
      how3Desc: 'Directe betaling, gratis ophaling',
      sectionTypesTitle: 'Alle voertuigen geaccepteerd',
      sectionTypesSubtitle: 'Ongeacht de staat van uw auto',
      type1: 'In goede staat',
      type2: 'Met problemen',
      type3: 'Pech',
      type4: 'Na ongeluk',
      type5: 'Motor defect',
      type6: 'Zonder keuring',
      sectionTestimonialsTitle: 'Zij vertrouwen ons',
      testimonial1: 'Uitstekende service! Mijn oude Clio werd binnen 24 uur gekocht. Aanbevolen.',
      testimonial1Author: 'Marie L., Brussel',
      testimonial2: 'Ik had een beschadigde auto die niemand wilde. Ze deden me een eerlijk aanbod.',
      testimonial2Author: 'Jean-Pierre D., Luik',
      testimonial3: 'Snel, efficiënt en eerlijk. De voorgestelde prijs voldeed aan mijn verwachtingen.',
      testimonial3Author: 'Sophie M., Namen',
      ctaTitle: 'Klaar om uw auto te verkopen?',
      ctaSubtitle: 'Krijg een gratis schatting in minder dan 2 minuten',
      ctaButton: 'Nu mijn auto schatten',
    },
    // Estimation form
    estimation: {
      title: 'Gratis schatting',
      subtitle: 'Vul het formulier in om uw aanbod te ontvangen',
      step1: 'Voertuig',
      step2: 'Foto\'s',
      step3: 'Contact',
      step4: 'Bevestiging',
      step1Title: 'Informatie over uw voertuig',
      brand: 'Merk',
      model: 'Model',
      year: 'Jaar',
      mileage: 'Kilometerstand',
      fuel: 'Brandstof',
      gearbox: 'Versnellingsbak',
      condition: 'Staat van het voertuig',
      registration: 'Kenteken (optioneel)',
      desiredPrice: 'Gewenste prijs (optioneel)',
      sellDelay: 'Wanneer wilt u verkopen? (optioneel)',
      select: 'Selecteer',
      selectCondition: 'Selecteer de huidige staat',
      selectDelay: 'Selecteer een termijn',
      fuelPetrol: 'Benzine',
      fuelDiesel: 'Diesel',
      fuelHybrid: 'Hybride',
      fuelElectric: 'Elektrisch',
      fuelLpg: 'LPG',
      gearboxManual: 'Manueel',
      gearboxAuto: 'Automatisch',
      conditionPerfect: 'Rijdt perfect',
      conditionIssues: 'Rijdt met problemen',
      conditionBroken: 'Rijdt niet (pech)',
      conditionAccident: 'Beschadigd',
      conditionEngineKO: 'Motor defect',
      conditionNoCT: 'Zonder keuring',
      conditionOther: 'Andere',
      delayImmediate: 'Onmiddellijk',
      delay1Week: 'Binnen 1 week',
      delay2Weeks: 'Binnen 2 weken',
      delay1Month: 'Binnen 1 maand',
      delayNotUrgent: 'Niet dringend',
      step2Title: 'Foto\'s van uw voertuig (optioneel)',
      step2Desc: 'Voeg tot 10 foto\'s toe voor een nauwkeurigere schatting',
      uploadText: 'Klik of sleep uw foto\'s hier',
      uploadHint: 'PNG, JPG tot 5MB elk',
      maxPhotos: 'Maximum 8 foto\'s toegestaan',
      step3Title: 'Uw contactgegevens',
      fullName: 'Volledige naam',
      phone: 'Telefoon',
      email: 'E-mail',
      postalCode: 'Postcode',
      city: 'Stad',
      rgpdConsent: 'Ik ga akkoord dat mijn gegevens worden gebruikt om mijn aankoopverzoek te verwerken.',
      rgpdLink: 'Bekijk ons privacybeleid',
      step4Title: 'Samenvatting van uw aanvraag',
      vehicle: 'Voertuig',
      location: 'Locatie',
      photosAttached: 'foto(\'s) bijgevoegd',
      callbackInfo: 'Wij bellen u binnen 2 uur terug',
      callbackHours: 'Maandag tot zaterdag, 9u tot 19u',
      previous: 'Vorige',
      next: 'Volgende',
      submit: 'Verstuur mijn aanvraag',
      submitting: 'Verzenden...',
      required: 'Verplicht',
      invalidEmail: 'Ongeldig e-mailadres',
      invalidPhone: 'Ongeldig nummer',
      mustAccept: 'U moet akkoord gaan',
      errorSubmit: 'Er is een fout opgetreden. Probeer het opnieuw.',
    },
    // Thank you page
    thankYou: {
      title: 'Bedankt voor uw aanvraag!',
      subtitle: 'Uw aanvraag is succesvol geregistreerd',
      reference: 'Referentie',
      nextSteps: 'Volgende stappen',
      step1: 'Onze expert analyseert uw aanvraag',
      step2: 'U ontvangt een telefoontje binnen 2 uur (werkdagen)',
      step3: 'We spreken een afspraak af',
      step4: 'Gratis ophaling en directe betaling',
      backHome: 'Terug naar home',
    },
    // How it works page
    howItWorks: {
      title: 'Hoe werkt het?',
      subtitle: 'Een eenvoudig en snel proces in 4 stappen',
      step1Title: 'Vul het formulier in',
      step1Desc: 'Beschrijf uw voertuig in enkele klikken: merk, model, staat, kilometerstand. Voeg foto\'s toe voor een nauwkeurigere schatting.',
      step2Title: 'Ontvang uw aanbod',
      step2Desc: 'Onze expert contacteert u binnen 2 uur met een vast en vrijblijvend aankoopvoorstel.',
      step3Title: 'Accepteer en plan',
      step3Desc: 'Als ons aanbod u bevalt, organiseren we de ophaling van uw voertuig op een datum die u uitkomt.',
      step4Title: 'Ontvang direct betaling',
      step4Desc: 'Bij de ophaling ontvangt u uw betaling. Wij zorgen voor alle administratieve papieren.',
      ctaTitle: 'Klaar om te beginnen?',
      ctaButton: 'Schat mijn auto',
    },
    // Vehicle types page
    vehicleTypes: {
      title: 'Voertuigtypes',
      subtitle: 'Wij kopen alle soorten voertuigen, ongeacht hun staat',
      type1Title: 'Voertuigen in goede staat',
      type1Desc: 'Rijdt uw auto perfect? Wij bieden u een eerlijke prijs gebaseerd op de markt.',
      type2Title: 'Voertuigen met problemen',
      type2Desc: 'Kleine mechanische, elektrische of cosmetische problemen? Geen probleem, wij kopen ze.',
      type3Title: 'Voertuigen met pech',
      type3Desc: 'Uw auto start niet meer? Wij komen langs en halen hem gratis op.',
      type4Title: 'Beschadigde voertuigen',
      type4Desc: 'Licht of zwaar ongeluk, wij kopen uw beschadigde voertuig.',
      type5Title: 'Motor defect',
      type5Desc: 'Kapotte motor, koppakking, turbo? Wij doen een aanbod.',
      type6Title: 'Zonder keuring',
      type6Desc: 'Keuring verlopen of geweigerd? Wij kopen uw voertuig zonder voorwaarden.',
      ctaTitle: 'Past uw voertuig?',
      ctaButton: 'Vraag een schatting aan',
    },
    // FAQ page
    faq: {
      title: 'Veelgestelde vragen',
      subtitle: 'Vind antwoorden op uw vragen',
      q1: 'Hoe werkt de aankoopservice?',
      a1: 'Het is eenvoudig: u vult ons online formulier in, wij contacteren u binnen 2 uur met een aanbod, en als het u bevalt, komen we uw voertuig ophalen en betalen we u onmiddellijk.',
      q2: 'Welke soorten voertuigen koopt u?',
      a2: 'Wij kopen alle voertuigen: in goede staat, met pech, beschadigd, zonder keuring, met defecte motor... Ongeacht het merk, model of leeftijd.',
      q3: 'Is de schatting gratis?',
      a3: 'Ja, de schatting is volledig gratis en vrijblijvend. U bent vrij om ons aanbod te accepteren of te weigeren.',
      q4: 'Binnen welke termijn ontvang ik een aanbod?',
      a4: 'Ons team contacteert u binnen 2 werkuren na ontvangst van uw aanvraag.',
      q5: 'Hoe verloopt de betaling?',
      a5: 'De betaling gebeurt onmiddellijk bij de ophaling van het voertuig, via bankoverschrijving of contant naar uw voorkeur.',
      q6: 'Is de ophaling gratis?',
      a6: 'Ja, de ophaling van uw voertuig is volledig gratis, waar u ook bent in België.',
      q7: 'Welke documenten moet ik verstrekken?',
      a7: 'U moet het kentekenbewijs (inschrijvingsbewijs), uw identiteitskaart en indien mogelijk het onderhoudsboekje verstrekken.',
      q8: 'Wat als mijn auto geen geldige keuring meer heeft?',
      a8: 'Geen probleem! Wij kopen voertuigen zonder geldige keuring. Het is zelfs onze specialiteit.',
      q9: 'Koopt u voertuigen die niet meer rijden?',
      a9: 'Ja, wij kopen voertuigen met pech, geïmmobiliseerd of die niet meer starten. Wij komen met een oplegger.',
      q10: 'In welke regio\'s werkt u?',
      a10: 'Wij werken in heel België: Wallonië, Brussel en Vlaanderen.',
      q11: 'Hoelang duurt de volledige procedure?',
      a11: 'Over het algemeen, tussen het eerste contact en de ophaling van uw voertuig, reken op 24 tot 48 uur.',
      q12: 'Kan ik annuleren na het accepteren van het aanbod?',
      a12: 'Ja, u kunt op elk moment annuleren vóór de daadwerkelijke ophaling van het voertuig, zonder kosten of boete.',
      stillQuestions: 'Heeft u nog andere vragen?',
      contactUs: 'Contacteer ons',
    },
    // About page
    about: {
      title: 'Over ons',
      subtitle: 'Uw betrouwbare partner voor de verkoop van voertuigen',
      intro: 'VendezVotreCar ontstond uit een eenvoudige vaststelling: uw auto verkopen, vooral wanneer hij problemen heeft, is vaak een ware hindernisbaan. Onze missie is om dit proces te vereenvoudigen.',
      mission: 'Onze missie',
      missionText: 'Elke Belg een eenvoudige, snelle en eerlijke oplossing bieden om zijn voertuig te verkopen, ongeacht de staat.',
      values: 'Onze waarden',
      value1Title: 'Transparantie',
      value1Desc: 'Duidelijke prijzen en uitleg bij procedures.',
      value2Title: 'Snelheid',
      value2Desc: 'Aanbod binnen 2 uur, ophaling binnen 48 uur.',
      value3Title: 'Respect',
      value3Desc: 'Een klantenservice die luistert en behulpzaam is.',
      stats: 'Enkele cijfers',
      stat1: 'Gekochte voertuigen',
      stat2: 'Tevreden klanten',
      stat3: 'Jaren ervaring',
    },
    // Contact page
    contact: {
      title: 'Contacteer ons',
      subtitle: 'Een vraag? Aarzel niet om ons te contacteren',
      formTitle: 'Stuur ons een bericht',
      name: 'Naam',
      email: 'E-mail',
      phone: 'Telefoon (optioneel)',
      message: 'Bericht',
      messagePlaceholder: 'Uw bericht...',
      send: 'Versturen',
      sending: 'Verzenden...',
      success: 'Bericht succesvol verzonden!',
      error: 'Fout bij verzenden. Probeer het opnieuw.',
      infoTitle: 'Onze contactgegevens',
      phoneLabel: 'Telefoon',
      emailLabel: 'E-mail',
      hoursLabel: 'Openingsuren',
      hours: 'Ma-Za: 9u-19u',
      zoneLabel: 'Werkgebied',
      zone: 'Heel België',
    },
    // Footer
    footer: {
      description: 'Aankoop van voertuigen in België. Alle soorten voertuigen geaccepteerd: met pech, beschadigd, zonder keuring.',
      quickLinks: 'Snelle links',
      legal: 'Juridisch',
      legalNotice: 'Juridische vermeldingen',
      privacy: 'Privacy',
      cookies: 'Cookies',
      copyright: 'Alle rechten voorbehouden.',
    },
    // Cookie banner
    cookies: {
      message: 'Wij gebruiken cookies om uw ervaring te verbeteren.',
      learnMore: 'Meer info',
      accept: 'Accepteren',
      reject: 'Weigeren',
    },
    // Common
    common: {
      loading: 'Laden...',
      error: 'Fout',
      notFound: 'Niet gevonden',
      back: 'Terug',
      close: 'Sluiten',
    },
  },
  en: {
    // Header
    nav: {
      home: 'Home',
      howItWorks: 'How it works',
      vehicleTypes: 'Vehicle types',
      faq: 'FAQ',
      about: 'About',
      contact: 'Contact',
      estimate: 'Get estimate',
    },
    // Home page
    home: {
      heroTitle: 'Sell your car',
      heroTitleHighlight: 'at the best price',
      heroSubtitle: 'Even if broken down, crashed or without inspection. Free estimate and fast purchase throughout Belgium.',
      heroCta: 'Get free estimate',
      heroSecondary: 'How does it work?',
      trustBadge1: 'Instant payment',
      trustBadge2: 'Free pickup',
      trustBadge3: 'Any condition',
      trustBadge4: 'No obligation',
      sectionWhyTitle: 'Why choose us?',
      sectionWhySubtitle: 'Thousands of Belgians trust us',
      why1Title: 'Guaranteed purchase',
      why1Desc: 'We buy all vehicles, regardless of their condition or age.',
      why2Title: 'Fair prices',
      why2Desc: 'Transparent estimate based on the real market.',
      why3Title: 'Fast service',
      why3Desc: 'Offer within 2 hours and pickup within 48 hours.',
      why4Title: 'No hassle',
      why4Desc: 'We handle everything: paperwork, pickup, payment.',
      sectionHowTitle: 'How does it work?',
      sectionHowSubtitle: 'Sell your car in 3 simple steps',
      how1Title: 'Describe your vehicle',
      how1Desc: 'Fill out our form in 2 minutes',
      how2Title: 'Receive your offer',
      how2Desc: 'Our expert calls you within 2 hours',
      how3Title: 'Sell and get paid',
      how3Desc: 'Instant payment, free pickup',
      sectionTypesTitle: 'All vehicles accepted',
      sectionTypesSubtitle: 'Whatever the condition of your car',
      type1: 'Good condition',
      type2: 'With issues',
      type3: 'Broken down',
      type4: 'Crashed',
      type5: 'Engine dead',
      type6: 'No inspection',
      sectionTestimonialsTitle: 'They trust us',
      testimonial1: 'Impeccable service! My old Clio was bought within 24 hours. Highly recommend.',
      testimonial1Author: 'Marie L., Brussels',
      testimonial2: 'I had a crashed car that nobody wanted. They made me a fair offer.',
      testimonial2Author: 'Jean-Pierre D., Liège',
      testimonial3: 'Fast, efficient and honest. The proposed price met my expectations.',
      testimonial3Author: 'Sophie M., Namur',
      ctaTitle: 'Ready to sell your car?',
      ctaSubtitle: 'Get a free estimate in less than 2 minutes',
      ctaButton: 'Estimate my car now',
    },
    // Estimation form
    estimation: {
      title: 'Free estimate',
      subtitle: 'Fill out the form to receive your offer',
      step1: 'Vehicle',
      step2: 'Photos',
      step3: 'Contact',
      step4: 'Confirmation',
      step1Title: 'Information about your vehicle',
      brand: 'Brand',
      model: 'Model',
      year: 'Year',
      mileage: 'Mileage',
      fuel: 'Fuel',
      gearbox: 'Gearbox',
      condition: 'Vehicle condition',
      registration: 'Registration (optional)',
      desiredPrice: 'Desired price (optional)',
      sellDelay: 'When do you want to sell? (optional)',
      select: 'Select',
      selectCondition: 'Select current condition',
      selectDelay: 'Select a timeframe',
      fuelPetrol: 'Petrol',
      fuelDiesel: 'Diesel',
      fuelHybrid: 'Hybrid',
      fuelElectric: 'Electric',
      fuelLpg: 'LPG',
      gearboxManual: 'Manual',
      gearboxAuto: 'Automatic',
      conditionPerfect: 'Runs perfectly',
      conditionIssues: 'Runs with issues',
      conditionBroken: 'Doesn\'t run (broken)',
      conditionAccident: 'Crashed',
      conditionEngineKO: 'Engine dead',
      conditionNoCT: 'No inspection',
      conditionOther: 'Other',
      delayImmediate: 'Immediately',
      delay1Week: 'Within 1 week',
      delay2Weeks: 'Within 2 weeks',
      delay1Month: 'Within 1 month',
      delayNotUrgent: 'Not urgent',
      step2Title: 'Photos of your vehicle (optional)',
      step2Desc: 'Add up to 10 photos for a more accurate estimate',
      uploadText: 'Click or drag your photos here',
      uploadHint: 'PNG, JPG up to 5MB each',
      maxPhotos: 'Maximum 8 photos allowed',
      step3Title: 'Your contact details',
      fullName: 'Full name',
      phone: 'Phone',
      email: 'Email',
      postalCode: 'Postal code',
      city: 'City',
      rgpdConsent: 'I agree that my data will be used to process my purchase request.',
      rgpdLink: 'See our privacy policy',
      step4Title: 'Summary of your request',
      vehicle: 'Vehicle',
      location: 'Location',
      photosAttached: 'photo(s) attached',
      callbackInfo: 'We\'ll call you back within 2 hours',
      callbackHours: 'Monday to Saturday, 9am to 7pm',
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit my request',
      submitting: 'Submitting...',
      required: 'Required',
      invalidEmail: 'Invalid email',
      invalidPhone: 'Invalid number',
      mustAccept: 'You must accept',
      errorSubmit: 'An error occurred. Please try again.',
    },
    // Thank you page
    thankYou: {
      title: 'Thank you for your request!',
      subtitle: 'Your request has been successfully registered',
      reference: 'Reference',
      nextSteps: 'Next steps',
      step1: 'Our expert analyzes your request',
      step2: 'You receive a call within 2 hours (business days)',
      step3: 'We schedule an appointment',
      step4: 'Free pickup and instant payment',
      backHome: 'Back to home',
    },
    // How it works page
    howItWorks: {
      title: 'How does it work?',
      subtitle: 'A simple and fast process in 4 steps',
      step1Title: 'Fill out the form',
      step1Desc: 'Describe your vehicle in a few clicks: brand, model, condition, mileage. Add photos for a more accurate estimate.',
      step2Title: 'Receive your offer',
      step2Desc: 'Our expert contacts you within 2 hours with a firm, no-obligation purchase proposal.',
      step3Title: 'Accept and schedule',
      step3Desc: 'If our offer suits you, we organize the pickup of your vehicle at a date that works for you.',
      step4Title: 'Get paid instantly',
      step4Desc: 'Upon pickup, you receive your payment. We handle all administrative paperwork.',
      ctaTitle: 'Ready to get started?',
      ctaButton: 'Estimate my car',
    },
    // Vehicle types page
    vehicleTypes: {
      title: 'Vehicle types',
      subtitle: 'We buy all types of vehicles, regardless of their condition',
      type1Title: 'Vehicles in good condition',
      type1Desc: 'Does your car run perfectly? We offer you a fair price based on the market.',
      type2Title: 'Vehicles with issues',
      type2Desc: 'Minor mechanical, electrical or cosmetic issues? No problem, we buy them.',
      type3Title: 'Broken down vehicles',
      type3Desc: 'Your car won\'t start? We come and pick it up for free.',
      type4Title: 'Crashed vehicles',
      type4Desc: 'Minor or major accident, we buy your crashed vehicle.',
      type5Title: 'Engine dead',
      type5Desc: 'Broken engine, head gasket, turbo? We make an offer.',
      type6Title: 'No inspection',
      type6Desc: 'Inspection expired or failed? We buy your vehicle unconditionally.',
      ctaTitle: 'Does your vehicle qualify?',
      ctaButton: 'Request an estimate',
    },
    // FAQ page
    faq: {
      title: 'Frequently asked questions',
      subtitle: 'Find answers to your questions',
      q1: 'How does the purchase service work?',
      a1: 'It\'s simple: you fill out our online form, we contact you within 2 hours with an offer, and if you like it, we pick up your vehicle and pay you immediately.',
      q2: 'What types of vehicles do you buy?',
      a2: 'We buy all vehicles: in good condition, broken down, crashed, without inspection, with dead engine... Regardless of brand, model or age.',
      q3: 'Is the estimate free?',
      a3: 'Yes, the estimate is completely free and without obligation. You are free to accept or decline our offer.',
      q4: 'How soon will I receive an offer?',
      a4: 'Our team contacts you within 2 business hours after receiving your request.',
      q5: 'How does payment work?',
      a5: 'Payment is made immediately upon pickup of the vehicle, by bank transfer or cash according to your preference.',
      q6: 'Is pickup free?',
      a6: 'Yes, pickup of your vehicle is completely free, wherever you are in Belgium.',
      q7: 'What documents do I need to provide?',
      a7: 'You need to provide the vehicle registration, your ID card, and if possible the service booklet.',
      q8: 'What if my car no longer has a valid inspection?',
      a8: 'No problem! We buy vehicles without valid inspection. It\'s even our specialty.',
      q9: 'Do you buy vehicles that no longer run?',
      a9: 'Yes, we buy broken down, immobilized vehicles or those that won\'t start. We come with a flatbed truck.',
      q10: 'In which regions do you operate?',
      a10: 'We operate throughout Belgium: Wallonia, Brussels and Flanders.',
      q11: 'How long does the complete procedure take?',
      a11: 'Generally, between the first contact and the pickup of your vehicle, expect 24 to 48 hours.',
      q12: 'Can I cancel after accepting the offer?',
      a12: 'Yes, you can cancel at any time before the actual pickup of the vehicle, without fees or penalty.',
      stillQuestions: 'Do you have other questions?',
      contactUs: 'Contact us',
    },
    // About page
    about: {
      title: 'About us',
      subtitle: 'Your trusted partner for vehicle sales',
      intro: 'VendezVotreCar was born from a simple observation: selling your car, especially when it has problems, is often an obstacle course. Our mission is to simplify this process.',
      mission: 'Our mission',
      missionText: 'Offer every Belgian a simple, fast and honest solution to sell their vehicle, regardless of its condition.',
      values: 'Our values',
      value1Title: 'Transparency',
      value1Desc: 'Clear prices and explained procedures.',
      value2Title: 'Speed',
      value2Desc: 'Offer within 2 hours, pickup within 48 hours.',
      value3Title: 'Respect',
      value3Desc: 'A customer service that listens and cares.',
      stats: 'Some figures',
      stat1: 'Vehicles purchased',
      stat2: 'Satisfied customers',
      stat3: 'Years of experience',
    },
    // Contact page
    contact: {
      title: 'Contact us',
      subtitle: 'A question? Don\'t hesitate to contact us',
      formTitle: 'Send us a message',
      name: 'Name',
      email: 'Email',
      phone: 'Phone (optional)',
      message: 'Message',
      messagePlaceholder: 'Your message...',
      send: 'Send',
      sending: 'Sending...',
      success: 'Message sent successfully!',
      error: 'Error sending. Please try again.',
      infoTitle: 'Our contact details',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      hoursLabel: 'Hours',
      hours: 'Mon-Sat: 9am-7pm',
      zoneLabel: 'Service area',
      zone: 'All of Belgium',
    },
    // Footer
    footer: {
      description: 'Vehicle purchase in Belgium. All types of vehicles accepted: broken down, crashed, without inspection.',
      quickLinks: 'Quick links',
      legal: 'Legal',
      legalNotice: 'Legal notice',
      privacy: 'Privacy',
      cookies: 'Cookies',
      copyright: 'All rights reserved.',
    },
    // Cookie banner
    cookies: {
      message: 'We use cookies to improve your experience.',
      learnMore: 'Learn more',
      accept: 'Accept',
      reject: 'Reject',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'Error',
      notFound: 'Not found',
      back: 'Back',
      close: 'Close',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Check localStorage first
    const saved = localStorage.getItem('vvc-language');
    if (saved && translations[saved]) {
      return saved;
    }
    return 'fr'; // Default to French
  });

  useEffect(() => {
    localStorage.setItem('vvc-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, languages: ['fr', 'nl', 'en'] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
